### ISSUE TITLE
Rebase with nautilus-admin

### ISSUE THREAD

**Issue by jbicha** [infirit/caja-admin#2]
Could you look at pulling the latest commits from nautilus-admin? In particular this commit looks interesting assuming you don't mind being limited to relatively recent distros.

https://github.com/brunonova/nautilus-admin/commit/01a96679c6454222d9ab0a7406e7d11087ccd7b8

**Comment by infirit** [comment]
I've decided to let this die out slowly. admin:// is the way forward and you really don't need an extension to hold your hand typing this in the addressbar 😉
