### ISSUE TITLE
How to install from source

### ISSUE THREAD

**Issue by Porrumentzio** [infirit/caja-admin#7]
I downloaded the sourcecode but there's no `CMakeLists.txt`, so I get error when running `cmake ..`. 
I saw that there's Meson on source, but running it, `meson builddir && sudo ninja -C builddir install`, does not seem to install the package or at least it is not usable on Caja.

**Comment by infirit** [comment]
The install prefix is important. Installing to the default /usr/local will most likely not work. Try.

```
meson -Dprefix=/usr builddir
sudo ninja -c builddir install
```

**Comment by Porrumentzio** [comment]
Thanks!

It is installed to `/usr/share/caja-python/extensions/caja-admin.py`, but even restarting Caja does not seem to show the extension. I'll try further.

**Comment by infirit** [comment]
The extension won't show up in the extrnsion list but python-caja should. Make sure you have that installed.

There may be errors so ``caja -q`` and then run it from a terminal. If it fails to load there should be an error.

**Comment by Porrumentzio** [comment]
Yes!
It worked now on my daily-use computer :)

Great extension, thanks!
