### ISSUE TITLE
not working in Bullseye

### ISSUE THREAD

**Issue by mexsudo** [infirit/caja-admin#8]

**Comment by mexsudo** [comment]
caja-admin adds some administrative actions to the right-click menu:
Open as Administrator: opens a folder in a new Caja window running with administrator (root) privileges.
Edit as Administrator: opens a file in a Pluma window running with administrator (root) privileges.
Run as Administrator: runs an executable file with administrator (root) privileges inside a MATE Terminal.

The menus do not have those entries to select.

It works as expected with Debian Mate Buster

**Comment by infirit** [comment]
Kill caja ``caja -q`` then from a terminal run caja and look for errors. But if it worked in buster something in debian broke and you should raise this with them. It works fine for me on arch linux.

**Comment by mexsudo** [comment]
thanks. 
no errors displayed

**Comment by infirit** [comment]
Make sure you have caja-python installed. You can check if it is in cajas plugin window.

**Comment by mexsudo** [comment]
caja-python is not in the Bullseye repos.
Debian has some work to do, Thanks

**Comment by DeeDeeRanged** [comment]
Debian bullseye has package python3-caja. For one reason or another it doesn't seam to work with python3-caja in bullseye.

**Comment by DeeDeeRanged** [comment]
Workaround for this issue install the package from Debian sid as that solves it.

**Comment by infirit** [comment]
> Workaround for this issue install the package from Debian sid as that solves it.

I don't use debian so thank for the workaround. There is not much I can do here other than to suggest you open a bug report on debian.

**Comment by mexsudo** [comment]
Problem Solved
I am happy to report that with a fresh install of Debian Bullseye Mate using the debian-bullseye-DI-alpha3-amd64-netinst.iso everything now works as expected.
thanks for indulging me.

I did not investigate what packages were installed or how it is configured.
somebody somewhat got us going.
Bullseye is showing promise :-)

**Comment by mexsudo** [comment]
pardon me for the huge bold text, that was unintended
